Localwire.Graphinder.WebVisualizer/Models/AlgorithmProgressReportViewModel.cs
namespace Localwire.Graphinder.WebVisualizer.Models
{
    using System;
    using System.Collections.Generic;

    public class AlgorithmProgressReportViewModel
    {
        public DateTime ReportDate { get; set; }
        public long ProcessorTime { get; set; }
        public ICollection<GraphNodeViewModel> CurrentSolution { get; set; }
        public uint CurrentFitness { get; set; }
        public bool Accepted { get; set; }
    }
}

Localwire.Graphinder.WebVisualizer/Models/AlgorithmRequestViewModel.cs
namespace Localwire.Graphinder.WebVisualizer.Models
{
    using System.ComponentModel.DataAnnotations;

    public abstract class AlgorithmRequestViewModel
    {
        [Required]
        [Range(20, 5000)]
        public uint NumberOfNodesToGenerate { get; set; }

        [Required]
        [Range(2, 50)]
        public uint MaxNeighboursForNode { get; set; }
    }
}

Localwire.Graphinder.WebVisualizer/Models/D3EdgeViewModel.cs
namespace Localwire.Graphinder.WebVisualizer.Models
{
    public class D3EdgeViewModel
    {
        public string Source { get; set; }
        public string Target { get; set; }
    }
}

Localwire.Graphinder.WebVisualizer/Models/D3GraphViewModel.cs
namespace Localwire.Graphinder.WebVisualizer.Models
{
    using System.Collections.Generic;

    public class D3GraphViewModel
    {
        public List<D3NodeViewModel> Nodes { get; set; }
        public List<D3EdgeViewModel> Edges { get; set; }
    }
}

Localwire.Graphinder.WebVisualizer/Models/D3NodeViewModel.cs
namespace Localwire.Graphinder.WebVisualizer.Models
{
    using System;

    public class D3NodeViewModel
    {
        public string Key { get; set; }
        public int ColorGroup { get; set; }
    }
}

Localwire.Graphinder.WebVisualizer/Models/GraphNodeViewModel.cs
namespace Localwire.Graphinder.WebVisualizer.Models
{
    using System.Collections.Generic;

    public class GraphNodeViewModel
    {
        public string Key { get; set; }
        public ICollection<string> Neighbours { get; set; }
    }
}

Localwire.Graphinder.WebVisualizer/Models/SimulatedAnnealingRequestViewModel.cs
namespace Localwire.Graphinder.WebVisualizer.Models
{
    using System.ComponentModel.DataAnnotations;

    public class SimulatedAnnealingRequestViewModel : AlgorithmRequestViewModel
    {
        //[Required]
        //[Range(50, 20000)]
        //public double InitialTemperature { get; set; }

        //[Required]
        //[Range(0.001, 0.75)]
        //public double CoolingRate { get; set; }
    }
}

Localwire.Graphinder.WebVisualizer/Controllers/AlgorithmsController.cs
using System.Web.Mvc;

namespace Localwire.Graphinder.WebVisualizer.Controllers
{
    using System;
    using System.Net;
    using System.Reactive.Linq;
    using Core.Algorithms.SimulatedAnnealing;
    using Core.Algorithms.SimulatedAnnealing.CoolingStrategies;
    using Core.Algorithms.SimulatedAnnealing.Setup;
    using Core.Graph;
    using Core.Problems.OptimizationProblems;
    using Helpers.Graph;
    using Hubs;
    using Microsoft.AspNet.SignalR;
    using Models;

    public class AlgorithmsController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SimulatedAnnealingPanel()
        {
            return View();
        }

        [HttpPost]
        public ActionResult StartSimulatedAnnealing(SimulatedAnnealingRequestViewModel algorithmRequest)
        {
            if (!ModelState.IsValid)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var graph = new Graph();
            graph.FillGraphRandomly(algorithmRequest.NumberOfNodesToGenerate, algorithmRequest.MaxNeighboursForNode);

            var hubContext = GlobalHost.ConnectionManager.GetHubContext<SimulatedAnnealingHub>();
            var algorithm = new SimulatedAnnealing(graph, new MinimumVertexCover(),
                new CoolingSetup(4000, 0.03, new AllRandomCooling()));
            
            algorithm.LaunchAlgorithm();
            algorithm.ProgressReportChanged.Subscribe(report =>
            {
                Observable.Timer(TimeSpan.FromMilliseconds(500)).Subscribe(_ =>
                {
                    hubContext.Clients.Group(algorithm.Id.ToString()).send(report.AsReportViewModel());
                });
            });

            return new JsonResult
            {
                Data = new { graph = graph.AsD3ViewModel(), hubId = algorithm.Id },
                ContentType = "application/x-javascript",
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }
    }
}

Localwire.Graphinder.WebVisualizer/Views/Algorithms/Index.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "..\\Shared\\_Layout.cshtml";
}

<br/>
<div class="jumbotron">
    <div class="container">
        <a href="@Url.Action("SimulatedAnnealingPanel")" type="button" class="btn btn-default btn-lg btn-block">Simulated Annealing</a>
        <button type="button" class="btn btn-default btn-lg btn-block">Genetic Algorithm</button>
    </div>
</div>

Localwire.Graphinder.WebVisualizer/Views/Algorithms/SimulatedAnnealingPanel.cshtml
@model Localwire.Graphinder.WebVisualizer.Models.SimulatedAnnealingRequestViewModel

@{
    ViewBag.Title = "title";
    Layout = "..\\Shared\\_Layout.cshtml";
}

<script src="@Url.Content("~/Scripts/jquery.validate.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")" type="text/javascript"></script>
<script src="https://d3js.org/d3.v4.min.js"></script>
<script src="@Url.Content("~/Scripts/jquery.signalR-2.2.1.min.js")"></script>
<script src="@Url.Content("~/signalr/hubs")"></script>
<script src="@Url.Content("~/Scripts/graphinder_simulated-annealing.js")" type="text/javascript"></script>

<h2>Simulated Annealing algorithm</h2>

<br/>

<div id="algorithm-settins" class="col-lg-6">
    @using (Html.BeginForm("StartSimulatedAnnealing", "Algorithms"))
    {
        <table>
            <tr>
                <td>@Html.LabelFor(m => m.NumberOfNodesToGenerate)</td>
                <td>@Html.EditorFor(m => m.NumberOfNodesToGenerate)</td>
            </tr>
            <tr>
                <td>@Html.LabelFor(m => m.MaxNeighboursForNode)</td>
                <td>@Html.EditorFor(m => m.MaxNeighboursForNode)</td>
            </tr>
            <tr>
                <td colspan="2">
                    <p></p>
                    <input type="submit" value="Send" style="width: 100%" class="btn btn-default"/>
                </td>
            </tr>
        </table>
    }
</div>

<div id="feed" class="col-lg-6">
    
</div>

<div id="graph-container" class="col-lg-12">
    <h4>Graph simulation</h4>

    <div class="graph-canvas">
        <svg width="1024" height="500"></svg>
    </div>

    <span>Graph d3.js implementation based on work of <a href="http://bl.ocks.org/mbostock/4600693">Mike Bostock</a></span>
</div>

Localwire.Graphinder.WebVisualizer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Algorithms", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Algorithms")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="container-body">
            @RenderBody()
        </div>
    </div>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>